version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_DB: employees
      POSTGRES_USER: employees
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
